name: bing_scraping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get_it: ^8.0.3
  localization: ^2.1.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  cloud_firestore: ^5.6.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  http_interceptor: ^2.0.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  flutter_svg: ^2.2.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.3.2
  flutter_gap: ^1.2.0
  url_launcher: ^6.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/pt_BR.json
    - assets/images/